[tool.ruff]
target-version = "py38"
lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["E501", "E701"] # line too long, multiple statements on one line
src = ["."]

[tool.black]
line-length = 120
target-version = ["py38"]

